#!/usr/bin/env python3
"""Generate SDK code samples for the API reference.

Writes the x-fern-examples code samples in fern/apis/*/overrides.yml.
The samples are single-sourced here: each SDK has one template, and the
Unleash Edge API reference derives its samples from the same templates with
the Edge base URL, so a fix applied here updates every copy.

Samples appear only on the entry endpoints (GET /api/client/features and
GET /api/frontend), where readers decide between hand-rolling an integration
and using an SDK. Other endpoints keep their auto-generated HTTP snippets;
notes explaining that SDKs call them automatically belong in the endpoint
descriptions upstream (unleash and unleash-edge repos).

Code patterns follow the SDK documentation in fern/pages/sdks/.

Regenerate with: python3 scripts/generate-sdk-code-samples.py
"""

import os
import textwrap

CLIENT_URL = "https://app.unleash-instance.example.com/api"
EDGE_URL = "https://edge.unleash-instance.example.com/api"

HEADER = """\
# Generated by scripts/generate-sdk-code-samples.py. Do not edit by hand;
# edit the templates in that script and regenerate.
#
# This file is deep-merged onto openapi.json at build time via the overrides
# entry in generators.yml. CI overwrites openapi.json on every spec refresh
# (scripts/fetch-openapi.mjs); never edit openapi.json by hand.
#
# A code sample whose language matches an auto-generated HTTP snippet
# (javascript, python, java, go, ruby, php, csharp, swift) replaces that
# snippet in the language dropdown; other languages (kotlin, dart, rust) get
# their own dropdown entry. The language key (not sdk) is intentional: sdk is
# only for Fern-generated SDKs, and the install field requires the language
# key per Fern's extension docs.
"""

BACKEND_NOTE = ("The SDK fetches all feature flag configurations from this "
                "endpoint at startup and polls for updates in the background.")
PHP_NOTE = ("The SDK fetches feature flag configurations from this endpoint "
            "on demand and caches them. It does not poll in the background.")
RUST_NOTE = ("The client does not poll on its own. Run the polling loop in "
             "a background task. The loop fetches feature flag "
             "configurations from this endpoint at the configured interval.")
FRONTEND_NOTE = ("The SDK fetches evaluated feature flags for the current "
                 "context from this endpoint and refreshes them in the "
                 "background.")


def comment(text, prefix="//", width=62):
    return "\n".join(f"{prefix} {line}" for line in textwrap.wrap(text, width))


def indent_inner(code, spaces):
    pad = " " * spaces
    return "\n".join(pad + line if line else "" for line in code.split("\n"))


# ---------------------------------------------------------------- backend SDKs

def node(url):
    return f"""\
import {{ initialize }} from 'unleash-client';

const unleash = initialize({{
  url: '{url}',
  appName: 'my-app',
  customHeaders: {{ Authorization: '<your-backend-token>' }},
}});

{comment(BACKEND_NOTE)}
unleash.on('ready', () => {{
  const enabled = unleash.isEnabled('my-feature');
}});
"""


def python(url):
    return f"""\
from UnleashClient import UnleashClient

client = UnleashClient(
    url="{url}",
    app_name="my-app",
    custom_headers={{'Authorization': '<your-backend-token>'}})

client.initialize_client()

{comment(BACKEND_NOTE, "#")}
enabled = client.is_enabled("my-feature")
"""


def java(url):
    return f"""\
UnleashConfig config = UnleashConfig.builder()
        .appName("my-app")
        .instanceId("my-instance")
        .unleashAPI("{url}")
        .apiKey("<your-backend-token>")
        .build();

Unleash unleash = new DefaultUnleash(config);

{comment(BACKEND_NOTE)}
boolean enabled = unleash.isEnabled("my-feature");
"""


def go(url):
    body = f"""\
err := unleash.Initialize(
    unleash.WithAppName("my-app"),
    unleash.WithUrl("{url}"),
    unleash.WithCustomHeaders(http.Header{{"Authorization": {{"<your-backend-token>"}}}}),
)
if err != nil {{
    panic(err)
}}
defer unleash.Close()
unleash.WaitForReady()

{comment(BACKEND_NOTE)}
enabled := unleash.IsEnabled("my-feature", unleash.FeatureOptions{{}})"""
    return f"""\
package main

import (
    "net/http"

    unleash "github.com/Unleash/unleash-go-sdk/v6"
)

func main() {{
{indent_inner(body, 4)}
}}
"""


def ruby(url):
    return f"""\
require 'unleash'

@unleash = Unleash::Client.new(
  app_name: 'my-app',
  url: '{url}',
  custom_http_headers: {{ 'Authorization': '<your-backend-token>' }}
)

{comment(BACKEND_NOTE, "#")}
enabled = @unleash.is_enabled?('my-feature')
"""


def php(url):
    return f"""\
use Unleash\\Client\\UnleashBuilder;

$unleash = UnleashBuilder::create()
    ->withAppName('my-app')
    ->withAppUrl('{url}')
    ->withInstanceId('my-instance')
    ->withHeader('Authorization', '<your-backend-token>')
    ->build();

{comment(PHP_NOTE)}
$enabled = $unleash->isEnabled('my-feature');
"""


def csharp(url):
    return f"""\
using Unleash;

var settings = new UnleashSettings()
{{
    AppName = "my-app",
    UnleashApi = new Uri("{url}"),
    CustomHttpHeaders = new Dictionary<string, string>()
    {{
        {{ "Authorization", "<your-backend-token>" }}
    }}
}};

var unleash = new DefaultUnleash(settings);

{comment(BACKEND_NOTE)}
var enabled = unleash.IsEnabled("my-feature");
"""


def rust(url):
    return f"""\
// The SDK reads its configuration from these environment variables:
// UNLEASH_API_URL={url}
// UNLEASH_CLIENT_SECRET=<your-backend-token>
let config = EnvironmentConfig::from_env()?;
let client = Arc::new(
    client::ClientBuilder::default()
        .enable_string_features()
        .into_client::<UserFeatures>(
            &config.api_url,
            &config.app_name,
            &config.instance_id,
            config.secret,
        )?,
);
client.register().await?;

{comment(RUST_NOTE)}
let poller = client.clone();
tokio::spawn(async move {{ poller.poll_for_updates().await }});
let enabled = client.is_enabled_str("my-feature", None, false);
"""


# --------------------------------------------------------------- frontend SDKs

def js_frontend(url):
    return f"""\
import {{ UnleashClient }} from 'unleash-proxy-client';

const unleash = new UnleashClient({{
    url: '{url}',
    clientKey: '<your-frontend-token>',
    appName: 'my-app',
}});

unleash.start();

{comment(FRONTEND_NOTE)}
unleash.on('ready', () => {{
  const enabled = unleash.isEnabled('my-feature');
}});
"""


def swift(url):
    return f"""\
import UnleashProxyClientSwift

var unleash = UnleashProxyClientSwift.UnleashClient(
    unleashUrl: "{url}",
    clientKey: "<your-frontend-token>",
    refreshInterval: 15,
    appName: "my-app"
)

unleash.start()

{comment(FRONTEND_NOTE)}
let enabled = unleash.isEnabled(name: "my-feature")
"""


def kotlin(url):
    return f"""\
val unleash = DefaultUnleash(
    androidContext = applicationContext,
    unleashConfig = UnleashConfig.newBuilder(appName = "my-app")
        .proxyUrl("{url}")
        .clientKey("<your-frontend-token>")
        .build()
)

unleash.start()

{comment(FRONTEND_NOTE)}
val enabled = unleash.isEnabled("my-feature")
"""


def dart(url):
    return f"""\
import 'package:unleash_proxy_client_flutter/unleash_proxy_client_flutter.dart';

final unleash = UnleashClient(
    url: Uri.parse('{url}'),
    clientKey: '<your-frontend-token>',
    appName: 'my-app');

unleash.start();

{comment(FRONTEND_NOTE)}
final enabled = unleash.isEnabled('my-feature');
"""


# (language key, dropdown name, install command, template)
BACKEND_LANGS = [
    ("javascript", "Node.js SDK", "npm install unleash-client", node),
    ("python", "Python SDK", "pip install UnleashClient", python),
    ("java", "Java SDK", "implementation(\"io.getunleash:unleash-client-java:<version>\")", java),
    ("go", "Go SDK", "go get github.com/Unleash/unleash-go-sdk/v6@latest", go),
    ("ruby", "Ruby SDK", "gem install unleash", ruby),
    ("php", "PHP SDK", "composer require unleash/client guzzlehttp/guzzle symfony/cache", php),
    ("csharp", ".NET SDK", "dotnet add package unleash.client", csharp),
    ("rust", "Rust SDK", "cargo add unleash-api-client", rust),
]

FRONTEND_LANGS = [
    ("javascript", "JavaScript SDK", "npm install unleash-proxy-client", js_frontend),
    ("swift", "iOS SDK", None, swift),
    ("kotlin", "Android SDK", "implementation(\"io.getunleash:unleash-android:<version>\")", kotlin),
    ("dart", "Flutter SDK", "flutter pub add unleash_proxy_client_flutter", dart),
]


# ------------------------------------------------------------- YAML emission

def emit_endpoint(path, method, langs, url):
    out = [f"  {path}:",
           f"    {method}:",
           "      x-fern-examples:",
           "        - code-samples:"]
    for language, name, install, template in langs:
        out.append(f"            - language: {language}")
        out.append(f"              name: {name}")
        if install:
            out.append(f"              install: {install}")
        out.append("              code: |")
        for line in template(url).rstrip("\n").split("\n"):
            out.append(f"                {line}" if line else "")
        out.append("")
    return "\n".join(out)


FILES = {
    "client-api": [("/api/client/features", "get", BACKEND_LANGS, CLIENT_URL + "/")],
    "frontend-api": [("/api/frontend", "get", FRONTEND_LANGS, CLIENT_URL + "/frontend")],
    "edge-api": [
        ("/api/client/features", "get", BACKEND_LANGS, EDGE_URL + "/"),
        ("/api/frontend", "get", FRONTEND_LANGS, EDGE_URL + "/frontend"),
    ],
}

repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for api, endpoints in FILES.items():
    content = HEADER + "paths:\n" + "\n".join(
        emit_endpoint(*endpoint) for endpoint in endpoints)
    path = os.path.join(repo_root, "fern", "apis", api, "overrides.yml")
    with open(path, "w") as f:
        f.write(content)
    print(f"wrote {path} ({len(content.splitlines())} lines)")
